export type Language = "en" | "it" | "es";

const copy = {
  en: {
    fieldGuide: "Habitat field guide",
    readOnly: "Read only",
    diagnosticProfile: "Diagnostic profile",
    symptoms: "Symptoms",
    likelyCauses: "Likely causes",
    treatment: "Treatment",
    prevention: "Prevention",
    fertilization: "Fertilization",
    waitingTitle: "Preparing the habitat view",
    waitingBody: "Atlarium is turning the latest tool result into a readable field guide.",
    emptyTitle: "No habitat data to show",
    emptyBody: "Ask ChatGPT to run an Atlarium search, profile, compatibility check or calculator.",
    errorTitle: "This result could not be displayed",
    errorBody: "The original Atlarium tool response is still available in the conversation.",
    details: "View details",
    expand: "Expand",
    collapse: "Return inline",
    askMore: "Ask a follow-up",
    water: "Water parameters",
    guides: "Care guides",
    watchPoints: "Watch points",
    recommendedActions: "Recommended actions",
    speciesReviewed: "Species reviewed",
    habitatPlan: "Habitat plan",
    candidates: "Recommended species",
    products: "Equipment and products",
    plants: "Plants",
    guidesSection: "Related guides",
    advisory: "Advisory result — verify against the real animals, equipment and water chemistry.",
    calculatedResult: "Calculated result",
    inputsAndAssumptions: "Inputs and assumptions",
    resultCount: (count: number) => `${count} public result${count === 1 ? "" : "s"}`,
    toolResult: "Atlarium result",
    compatibility: "Compatibility review",
  },
  it: {
    fieldGuide: "Guida naturalistica habitat",
    readOnly: "Sola lettura",
    diagnosticProfile: "Profilo diagnostico",
    symptoms: "Sintomi",
    likelyCauses: "Cause probabili",
    treatment: "Intervento",
    prevention: "Prevenzione",
    fertilization: "Fertilizzazione",
    waitingTitle: "Preparazione della vista habitat",
    waitingBody: "Atlarium sta trasformando il risultato del tool in una guida leggibile.",
    emptyTitle: "Nessun dato habitat da mostrare",
    emptyBody: "Chiedi a ChatGPT di eseguire una ricerca, un profilo, una compatibilità o un calcolo Atlarium.",
    errorTitle: "Impossibile visualizzare il risultato",
    errorBody: "La risposta originale del tool Atlarium resta disponibile nella conversazione.",
    details: "Vedi dettagli",
    expand: "Espandi",
    collapse: "Torna inline",
    askMore: "Chiedi un approfondimento",
    water: "Parametri dell'acqua",
    guides: "Guide di cura",
    watchPoints: "Punti di attenzione",
    recommendedActions: "Azioni consigliate",
    speciesReviewed: "Specie analizzate",
    habitatPlan: "Piano habitat",
    candidates: "Specie consigliate",
    products: "Attrezzatura e prodotti",
    plants: "Piante",
    guidesSection: "Guide correlate",
    advisory: "Risultato indicativo — verifica animali reali, attrezzatura e chimica dell'acqua.",
    calculatedResult: "Risultato calcolato",
    inputsAndAssumptions: "Input e presupposti",
    resultCount: (count: number) => `${count} risultat${count === 1 ? "o" : "i"} pubblic${count === 1 ? "o" : "i"}`,
    toolResult: "Risultato Atlarium",
    compatibility: "Valutazione di compatibilità",
  },
  es: {
    fieldGuide: "Guía de campo del hábitat",
    readOnly: "Solo lectura",
    diagnosticProfile: "Perfil diagnóstico",
    symptoms: "Síntomas",
    likelyCauses: "Causas probables",
    treatment: "Intervención",
    prevention: "Prevención",
    fertilization: "Fertilización",
    waitingTitle: "Preparando la vista del hábitat",
    waitingBody: "Atlarium está convirtiendo el resultado de la herramienta en una guía legible.",
    emptyTitle: "No hay datos del hábitat para mostrar",
    emptyBody: "Pide a ChatGPT una búsqueda, perfil, compatibilidad o cálculo de Atlarium.",
    errorTitle: "No se pudo mostrar el resultado",
    errorBody: "La respuesta original de Atlarium sigue disponible en la conversación.",
    details: "Ver detalles",
    expand: "Ampliar",
    collapse: "Volver a inline",
    askMore: "Pedir más detalles",
    water: "Parámetros del agua",
    guides: "Guías de cuidado",
    watchPoints: "Puntos de atención",
    recommendedActions: "Acciones recomendadas",
    speciesReviewed: "Especies revisadas",
    habitatPlan: "Plan de hábitat",
    candidates: "Especies recomendadas",
    products: "Equipos y productos",
    plants: "Plantas",
    guidesSection: "Guías relacionadas",
    advisory: "Resultado orientativo — verifica animales, equipo y química del agua reales.",
    calculatedResult: "Resultado calculado",
    inputsAndAssumptions: "Datos y supuestos",
    resultCount: (count: number) => `${count} resultado${count === 1 ? "" : "s"} público${count === 1 ? "" : "s"}`,
    toolResult: "Resultado de Atlarium",
    compatibility: "Revisión de compatibilidad",
  },
} as const;

export function languageFrom(value: unknown): Language {
  const normalized = String(value ?? "").toLowerCase();
  if (normalized.startsWith("it")) return "it";
  if (normalized.startsWith("es")) return "es";
  return "en";
}

export function useCopy(language: Language) {
  return copy[language];
}
