export type Language = "en" | "it" | "es";

const metricLabels: Record<Language, Record<string, string>> = {
  en: {
    Tank: "Tank",
    Volume: "Volume",
    Flow: "Flow",
    Temperature: "Temperature",
    Care: "Care",
    Compatibility: "Compatibility",
    Dose: "Dose",
    "Weekly total": "Weekly total",
    Category: "Category",
    "Use case": "Use case",
    "Gross Volume Liters": "Gross volume",
    "Estimated Net Volume Liters": "Estimated net volume",
    "Length Cm": "Length",
    "Width Cm": "Width",
    "Height Cm": "Height",
    "Displacement Percent": "Estimated displacement",
    "Weekly Total Ml": "Weekly total",
    "Dose Ml": "Dose",
    "Frequency Per Week": "Weekly frequency",
    "Target Nitrate Ppm": "Target nitrate",
    "Target Phosphate Ppm": "Target phosphate",
  },
  it: {
    Tank: "Vasca",
    Volume: "Volume",
    Flow: "Portata",
    Temperature: "Temperatura",
    Care: "Difficoltà",
    Compatibility: "Compatibilità",
    Dose: "Dose",
    "Weekly total": "Totale settimanale",
    Category: "Categoria",
    "Use case": "Utilizzo",
    "Gross Volume Liters": "Volume lordo",
    "Estimated Net Volume Liters": "Volume netto stimato",
    "Length Cm": "Lunghezza",
    "Width Cm": "Larghezza",
    "Height Cm": "Altezza",
    "Displacement Percent": "Ingombro stimato",
    "Weekly Total Ml": "Totale settimanale",
    "Dose Ml": "Dose",
    "Frequency Per Week": "Frequenza settimanale",
    "Target Nitrate Ppm": "Nitrati obiettivo",
    "Target Phosphate Ppm": "Fosfati obiettivo",
  },
  es: {
    Tank: "Acuario",
    Volume: "Volumen",
    Flow: "Caudal",
    Temperature: "Temperatura",
    Care: "Dificultad",
    Compatibility: "Compatibilidad",
    Dose: "Dosis",
    "Weekly total": "Total semanal",
    Category: "Categoría",
    "Use case": "Uso",
    "Gross Volume Liters": "Volumen bruto",
    "Estimated Net Volume Liters": "Volumen neto estimado",
    "Length Cm": "Longitud",
    "Width Cm": "Anchura",
    "Height Cm": "Altura",
    "Displacement Percent": "Desplazamiento estimado",
    "Weekly Total Ml": "Total semanal",
    "Dose Ml": "Dosis",
    "Frequency Per Week": "Frecuencia semanal",
    "Target Nitrate Ppm": "Nitrato objetivo",
    "Target Phosphate Ppm": "Fosfato objetivo",
  },
};

const calculationLabels: Record<Language, Record<string, string>> = {
  en: {},
  it: {
    "Above recommendation": "Sopra la raccomandazione",
    "Above target": "Sopra l'obiettivo",
    "Actual weekly dose": "Dose settimanale effettiva",
    "Analyzed products": "Prodotti analizzati",
    "Aquarium volume": "Volume dell'acquario",
    "Aquarium weight": "Peso dell'acquario",
    "Base area": "Area della base",
    "Below recommendation": "Sotto la raccomandazione",
    "Below target": "Sotto l'obiettivo",
    "Boron": "Boro",
    "Brand": "Marchio",
    "Calcium": "Calcio",
    "Carbonate hardness": "Durezza carbonatica",
    "Catalog dose": "Dose di catalogo",
    "Celsius": "Celsius",
    "Centimeters": "Centimetri",
    "Conductivity": "Conducibilità",
    "Contains macronutrients": "Contiene macronutrienti",
    "Contains micronutrients": "Contiene micronutrienti",
    "Contains macros": "Contiene macroelementi",
    "Contains micros": "Contiene microelementi",
    "Copper": "Rame",
    "Covered": "Coperti",
    "Current": "Attuale",
    "Daily consumption": "Consumo giornaliero",
    "Daily cost": "Costo giornaliero",
    "Days": "Giorni",
    "Deficit": "Carenza",
    "Delivered": "Apportato",
    "Density": "Densità",
    "Difference": "Differenza",
    "Dilution": "Diluizione",
    "Dilution factor": "Fattore di diluizione",
    "Dimensions": "Dimensioni",
    "Dose per application": "Dose per somministrazione",
    "Electricity": "Elettricità",
    "Equipment": "Attrezzatura",
    "Equipment requirements": "Requisiti dell'attrezzatura",
    "Fertilization plan": "Piano di fertilizzazione",
    "Fertilizer dose": "Dose di fertilizzante",
    "Footprint": "Superficie occupata",
    "Freeboard": "Bordo libero",
    "French hardness": "Durezza francese",
    "Front area": "Area frontale",
    "Frequency": "Frequenza",
    "General hardness": "Durezza totale",
    "Glass": "Vetro",
    "Grams": "Grammi",
    "Gross volume": "Volume lordo",
    "Hardscape": "Arredi e rocce",
    "Heater": "Riscaldatore",
    "In range": "Nel range",
    "Inches": "Pollici",
    "Iron": "Ferro",
    "Items": "Elementi",
    "Kilograms": "Chilogrammi",
    "Length": "Lunghezza",
    "Level": "Livello",
    "Lighting": "Illuminazione",
    "Liters": "Litri",
    "Lumens per liter": "Lumen per litro",
    "Magnesium": "Magnesio",
    "Manganese": "Manganese",
    "Maximum applications": "Somministrazioni massime",
    "Maximum weekly dose": "Dose settimanale massima",
    "Method": "Metodo",
    "Milliequivalents": "Milliequivalenti",
    "Milliliters": "Millilitri",
    "Millimeters": "Millimetri",
    "Millimoles": "Millimoli",
    "Minimum applications": "Somministrazioni minime",
    "Minimum power": "Potenza minima",
    "Minimum weekly dose": "Dose settimanale minima",
    "Missing measurements": "Misurazioni mancanti",
    "Monthly cost": "Costo mensile",
    "Molybdenum": "Molibdeno",
    "Net volume": "Volume netto",
    "Nitrogen": "Azoto",
    "Nutrient": "Nutriente",
    "Nutrient coverage": "Copertura dei nutrienti",
    "Nutrient gaps": "Carenze nutritive",
    "Nutrients with targets": "Nutrienti con obiettivo",
    "Nutrients": "Nutrienti",
    "Ounces": "Once",
    "Feet": "Piedi",
    "Fluid ounces": "Once liquide",
    "Parts per million": "Parti per milione",
    "Partial": "Parziale",
    "Per week": "Alla settimana",
    "Phosphorus": "Fosforo",
    "Potassium": "Potassio",
    "Pounds": "Libbre",
    "Per change": "Per cambio",
    "Preset products": "Prodotti del preset",
    "Product specifications": "Specifiche del prodotto",
    "Products": "Prodotti",
    "Proposals": "Proposte",
    "Recommended heater power": "Potenza riscaldatore consigliata",
    "Recommended dose": "Dose consigliata",
    "Recommended maximum": "Massimo consigliato",
    "Recommended minimum": "Minimo consigliato",
    "Recommended power": "Potenza consigliata",
    "Regime preset": "Regime preimpostato",
    "Remaining after changes": "Residuo dopo i cambi",
    "Removed after changes": "Rimosso dopo i cambi",
    "Residual": "Residuo",
    "Salinity": "Salinità",
    "Salt to add": "Sale da aggiungere",
    "Scheduled applications": "Somministrazioni programmate",
    "Scheduled products": "Prodotti programmati",
    "Score": "Punteggio",
    "Side area": "Area laterale",
    "Sizing factor": "Fattore di dimensionamento",
    "Source 1": "Sorgente 1",
    "Source 1 share": "Quota sorgente 1",
    "Source 2 share": "Quota sorgente 2",
    "Source 2": "Sorgente 2",
    "Specific gravity": "Peso specifico",
    "Status": "Stato",
    "Sub Type": "Sottotipo",
    "Substrate": "Substrato",
    "Substrate volume": "Volume del substrato",
    "Tank surfaces": "Superfici della vasca",
    "Tank volume": "Volume vasca",
    "Target comparison": "Confronto con gli obiettivi",
    "Target": "Obiettivo",
    "Temperature difference": "Differenza di temperatura",
    "Total weight": "Peso totale",
    "Unit conversion": "Conversione delle unità",
    "Unknown products": "Prodotti sconosciuti",
    "US gallons": "Galloni USA",
    "UK gallons": "Galloni UK",
    "Valid mix": "Miscela valida",
    "Water change": "Cambio d'acqua",
    "Water chemistry": "Chimica dell'acqua",
    "Water height": "Altezza dell'acqua",
    "Water mix": "Miscela d'acqua",
    "Water weight": "Peso dell'acqua",
    "Watts per liter": "Watt per litro",
    "Weekly delivery": "Apporto settimanale",
    "Weekly dose totals": "Totali delle dosi settimanali",
    "Weekly recommendation": "Raccomandazione settimanale",
    "Weekly totals": "Totali settimanali",
    "Weight breakdown": "Dettaglio del peso",
    "Weight": "Peso",
    "Warnings": "Avvertenze",
    "Yearly cost": "Costo annuale",
    "Zinc": "Zinco",
    "Flow Rate Liters Hour": "Portata",
  },
  es: {
    "Above recommendation": "Por encima de la recomendación",
    "Above target": "Por encima del objetivo",
    "Actual weekly dose": "Dosis semanal real",
    "Analyzed products": "Productos analizados",
    "Aquarium volume": "Volumen del acuario",
    "Aquarium weight": "Peso del acuario",
    "Base area": "Área de la base",
    "Below recommendation": "Por debajo de la recomendación",
    "Below target": "Por debajo del objetivo",
    "Boron": "Boro",
    "Brand": "Marca",
    "Calcium": "Calcio",
    "Carbonate hardness": "Dureza de carbonatos",
    "Catalog dose": "Dosis de catálogo",
    "Celsius": "Celsius",
    "Centimeters": "Centímetros",
    "Conductivity": "Conductividad",
    "Contains macronutrients": "Contiene macronutrientes",
    "Contains micronutrients": "Contiene micronutrientes",
    "Contains macros": "Contiene macronutrientes",
    "Contains micros": "Contiene micronutrientes",
    "Copper": "Cobre",
    "Covered": "Cubiertos",
    "Current": "Actual",
    "Daily consumption": "Consumo diario",
    "Daily cost": "Coste diario",
    "Days": "Días",
    "Deficit": "Déficit",
    "Delivered": "Aportado",
    "Density": "Densidad",
    "Difference": "Diferencia",
    "Dilution": "Dilución",
    "Dilution factor": "Factor de dilución",
    "Dimensions": "Dimensiones",
    "Dose per application": "Dosis por aplicación",
    "Electricity": "Electricidad",
    "Equipment": "Equipo",
    "Equipment requirements": "Requisitos del equipo",
    "Fertilization plan": "Plan de fertilización",
    "Fertilizer dose": "Dosis de fertilizante",
    "Footprint": "Superficie ocupada",
    "Freeboard": "Borde libre",
    "French hardness": "Dureza francesa",
    "Front area": "Área frontal",
    "Frequency": "Frecuencia",
    "General hardness": "Dureza general",
    "Glass": "Vidrio",
    "Grams": "Gramos",
    "Gross volume": "Volumen bruto",
    "Hardscape": "Rocas y decoración",
    "Heater": "Calentador",
    "In range": "En rango",
    "Inches": "Pulgadas",
    "Iron": "Hierro",
    "Items": "Elementos",
    "Kilograms": "Kilogramos",
    "Length": "Longitud",
    "Level": "Nivel",
    "Lighting": "Iluminación",
    "Liters": "Litros",
    "Lumens per liter": "Lúmenes por litro",
    "Magnesium": "Magnesio",
    "Manganese": "Manganeso",
    "Maximum applications": "Aplicaciones máximas",
    "Maximum weekly dose": "Dosis semanal máxima",
    "Method": "Método",
    "Milliequivalents": "Miliequivalentes",
    "Milliliters": "Mililitros",
    "Millimeters": "Milímetros",
    "Millimoles": "Milimoles",
    "Minimum applications": "Aplicaciones mínimas",
    "Minimum power": "Potencia mínima",
    "Minimum weekly dose": "Dosis semanal mínima",
    "Missing measurements": "Mediciones ausentes",
    "Monthly cost": "Coste mensual",
    "Molybdenum": "Molibdeno",
    "Net volume": "Volumen neto",
    "Nitrogen": "Nitrógeno",
    "Nutrient": "Nutriente",
    "Nutrient coverage": "Cobertura de nutrientes",
    "Nutrient gaps": "Carencias de nutrientes",
    "Nutrients with targets": "Nutrientes con objetivo",
    "Nutrients": "Nutrientes",
    "Ounces": "Onzas",
    "Feet": "Pies",
    "Fluid ounces": "Onzas líquidas",
    "Parts per million": "Partes por millón",
    "Partial": "Parcial",
    "Per week": "Por semana",
    "Phosphorus": "Fósforo",
    "Potassium": "Potasio",
    "Pounds": "Libras",
    "Per change": "Por cambio",
    "Preset products": "Productos del preset",
    "Product specifications": "Especificaciones del producto",
    "Products": "Productos",
    "Proposals": "Propuestas",
    "Recommended heater power": "Potencia recomendada del calentador",
    "Recommended dose": "Dosis recomendada",
    "Recommended maximum": "Máximo recomendado",
    "Recommended minimum": "Mínimo recomendado",
    "Recommended power": "Potencia recomendada",
    "Regime preset": "Régimen preestablecido",
    "Remaining after changes": "Restante tras los cambios",
    "Removed after changes": "Retirado tras los cambios",
    "Residual": "Residual",
    "Salinity": "Salinidad",
    "Salt to add": "Sal a añadir",
    "Scheduled applications": "Aplicaciones programadas",
    "Scheduled products": "Productos programados",
    "Score": "Puntuación",
    "Side area": "Área lateral",
    "Sizing factor": "Factor de dimensionado",
    "Source 1": "Fuente 1",
    "Source 1 share": "Proporción fuente 1",
    "Source 2 share": "Proporción fuente 2",
    "Source 2": "Fuente 2",
    "Specific gravity": "Gravedad específica",
    "Status": "Estado",
    "Sub Type": "Subtipo",
    "Substrate": "Sustrato",
    "Substrate volume": "Volumen del sustrato",
    "Tank surfaces": "Superficies del acuario",
    "Tank volume": "Volumen del acuario",
    "Target comparison": "Comparación con objetivos",
    "Target": "Objetivo",
    "Temperature difference": "Diferencia de temperatura",
    "Total weight": "Peso total",
    "Unit conversion": "Conversión de unidades",
    "Unknown products": "Productos desconocidos",
    "US gallons": "Galones EE. UU.",
    "UK gallons": "Galones UK",
    "Valid mix": "Mezcla válida",
    "Water change": "Cambio de agua",
    "Water chemistry": "Química del agua",
    "Water height": "Altura del agua",
    "Water mix": "Mezcla de agua",
    "Water weight": "Peso del agua",
    "Watts per liter": "Vatios por litro",
    "Weekly delivery": "Aporte semanal",
    "Weekly dose totals": "Totales de dosis semanales",
    "Weekly recommendation": "Recomendación semanal",
    "Weekly totals": "Totales semanales",
    "Weight breakdown": "Desglose del peso",
    "Weight": "Peso",
    "Warnings": "Advertencias",
    "Yearly cost": "Coste anual",
    "Zinc": "Zinc",
    "Flow Rate Liters Hour": "Caudal",
  },
};

const statusLabels: Record<Language, Record<string, string>> = {
  en: {
    above: "Above", algae: "Algae", bacterial: "Bacterial", balanced: "Balanced", below: "Below",
    brackish: "Brackish", compatible: "Compatible", "compatible with caution": "Compatible with caution",
    compatible_with_caution: "Compatible with caution", covered: "Covered", disease: "Disease", easy: "Easy",
    environmental: "Environmental", equipment: "Equipment", excellent: "Excellent", expert: "Expert",
    false: "No", fertilizer: "Fertilizer", filter: "Filter", freshwater: "Freshwater", fungal: "Fungal",
    good: "Good", high: "High", in_range: "In range", incompatible: "Incompatible", intermediate: "Intermediate",
    internal: "Internal", liquid: "Liquid", low: "Low", marine: "Marine", medicine: "Medicine", medium: "Medium",
    missing: "Missing", missing_measurement: "Missing measurement", natural: "Natural", no_target: "No target",
    nutritional_deficiency: "Nutritional deficiency", once_or_twice_weekly: "Once or twice weekly",
    "once or twice weekly": "Once or twice weekly", optimal: "Optimal", parasite: "Parasitic", partial: "Partial",
    per_week: "Per week", plant_problem: "Plant problem", recommended: "Recommended", review: "Review", safe: "Safe",
    semi_aquatic: "Semi-aquatic", terrestrial: "Terrestrial", true: "Yes", unknown: "Unknown", viral: "Viral", yes: "Yes",
  },
  it: {
    above: "Sopra", algae: "Alga", bacterial: "Batterica", balanced: "Bilanciato", below: "Sotto",
    brackish: "Acqua salmastra", compatible: "Compatibili", "compatible with caution": "Compatibili con cautela",
    compatible_with_caution: "Compatibili con cautela", covered: "Coperto", disease: "Malattia", easy: "Facile",
    environmental: "Ambientale", equipment: "Attrezzatura", excellent: "Eccellente", expert: "Esperto",
    false: "No", fertilizer: "Fertilizzante", filter: "Filtro", freshwater: "Acqua dolce", fungal: "Fungina",
    good: "Buono", high: "Alto", in_range: "Nel range", incompatible: "Non compatibili", intermediate: "Intermedio",
    internal: "Interno", liquid: "Liquido", low: "Basso", marine: "Acqua marina", medicine: "Medicinale", medium: "Medio",
    missing: "Mancante", missing_measurement: "Misurazione mancante", natural: "Naturale", no_target: "Nessun obiettivo",
    nutritional_deficiency: "Carenza nutrizionale", once_or_twice_weekly: "Una o due volte a settimana",
    "once or twice weekly": "Una o due volte a settimana", optimal: "Ottimale", parasite: "Parassitaria", partial: "Parziale",
    per_week: "Alla settimana", plant_problem: "Problema della pianta", recommended: "Consigliato", review: "Da verificare",
    safe: "Sicuro", semi_aquatic: "Semiaquatico", terrestrial: "Terrestre", true: "Sì", unknown: "Sconosciuto",
    viral: "Virale", yes: "Sì",
  },
  es: {
    above: "Por encima", algae: "Alga", bacterial: "Bacteriana", balanced: "Equilibrado", below: "Por debajo",
    brackish: "Agua salobre", compatible: "Compatibles", "compatible with caution": "Compatibles con precaución",
    compatible_with_caution: "Compatibles con precaución", covered: "Cubierto", disease: "Enfermedad", easy: "Fácil",
    environmental: "Ambiental", equipment: "Equipo", excellent: "Excelente", expert: "Experto", false: "No",
    fertilizer: "Fertilizante", filter: "Filtro", freshwater: "Agua dulce", fungal: "Fúngica", good: "Bueno",
    high: "Alto", in_range: "En rango", incompatible: "Incompatibles", intermediate: "Intermedio", internal: "Interno",
    liquid: "Líquido", low: "Bajo", marine: "Agua marina", medicine: "Medicamento", medium: "Medio",
    missing: "Ausente", missing_measurement: "Medición ausente", natural: "Natural", no_target: "Sin objetivo",
    nutritional_deficiency: "Deficiencia nutricional", once_or_twice_weekly: "Una o dos veces por semana",
    "once or twice weekly": "Una o dos veces por semana", optimal: "Óptimo", parasite: "Parasitaria", partial: "Parcial",
    per_week: "Por semana", plant_problem: "Problema de la planta", recommended: "Recomendado", review: "Revisar",
    safe: "Seguro", semi_aquatic: "Semiacuático", terrestrial: "Terrestre", true: "Sí", unknown: "Desconocido",
    viral: "Vírica", yes: "Sí",
  },
};

function localizedLabel(language: Language, label: string) {
  return calculationLabels[language][label] ?? metricLabels[language][label] ?? label;
}

function localizedStatus(language: Language, status: string) {
  return status
    .split(" · ")
    .map((part) => {
      const normalized = part.trim().toLowerCase();
      const normalizedToken = normalized.replace(/[\s-]+/g, "_");
      return statusLabels[language][normalized]
        ?? statusLabels[language][normalizedToken]
        ?? part.replaceAll("_", " ");
    })
    .join(" · ");
}

const copy = {
  en: {
    fieldGuide: "Habitat field guide",
    readOnly: "Read only",
    diagnosticProfile: "Diagnostic profile",
    productProfile: "Product profile",
    overview: "Overview",
    specifications: "Specifications",
    symptoms: "Symptoms",
    likelyCauses: "Likely causes",
    treatment: "Treatment",
    prevention: "Prevention",
    fertilization: "Fertilization",
    waitingTitle: "Preparing the habitat view",
    waitingBody: "Atlarium is turning the latest tool result into a readable field guide.",
    emptyTitle: "No habitat data to show",
    emptyBody: "Ask ChatGPT to run an Atlarium search, profile, compatibility check or calculator.",
    errorTitle: "This result could not be displayed",
    errorBody: "The original Atlarium tool response is still available in the conversation.",
    details: "View details",
    expand: "Expand",
    collapse: "Return inline",
    askMore: "Ask a follow-up",
    water: "Water parameters",
    guides: "Care guides",
    watchPoints: "Watch points",
    recommendedActions: "Recommended actions",
    speciesReviewed: "Species reviewed",
    habitatPlan: "Habitat plan",
    candidates: "Recommended species",
    products: "Equipment and products",
    plants: "Plants",
    guidesSection: "Related guides",
    advisory: "Advisory result — verify against the real animals, equipment and water chemistry.",
    calculationAdvisory: "Calculated advisory — verify inputs, units, product labels and real system conditions.",
    calculatedResult: "Calculated result",
    incompleteCalculation: "The calculation needs more complete input before it can produce a reliable result.",
    inputsAndAssumptions: "Inputs and assumptions",
    resultCount: (count: number) => `${count} public result${count === 1 ? "" : "s"}`,
    toolResult: "Atlarium result",
    compatibility: "Compatibility review",
    careFollowUp: (title: string) => `Explain the most important care implications for ${title} using the Atlarium result above.`,
    productFollowUp: (title: string) => `Explain the most important selection and sizing considerations for ${title} using the Atlarium result above.`,
    compatibilityFollowUp: (level: string) => `Explain how to manage this compatibility result safely: ${level}.`,
    habitatFollowUp: "Refine this Atlarium habitat plan while keeping it read-only.",
    diagnosticFollowUp: (title: string) => `Explain the safest next checks for this Atlarium diagnostic result: ${title}.`,
    metricLabel: (label: string) => localizedLabel("en", label),
    statusLabel: (status: string) => localizedStatus("en", status),
  },
  it: {
    fieldGuide: "Guida naturalistica habitat",
    readOnly: "Sola lettura",
    diagnosticProfile: "Profilo diagnostico",
    productProfile: "Profilo prodotto",
    overview: "Panoramica",
    specifications: "Specifiche",
    symptoms: "Sintomi",
    likelyCauses: "Cause probabili",
    treatment: "Intervento",
    prevention: "Prevenzione",
    fertilization: "Fertilizzazione",
    waitingTitle: "Preparazione della vista habitat",
    waitingBody: "Atlarium sta trasformando il risultato del tool in una guida leggibile.",
    emptyTitle: "Nessun dato habitat da mostrare",
    emptyBody: "Chiedi a ChatGPT di eseguire una ricerca, un profilo, una compatibilità o un calcolo Atlarium.",
    errorTitle: "Impossibile visualizzare il risultato",
    errorBody: "La risposta originale del tool Atlarium resta disponibile nella conversazione.",
    details: "Vedi dettagli",
    expand: "Espandi",
    collapse: "Torna inline",
    askMore: "Chiedi un approfondimento",
    water: "Parametri dell'acqua",
    guides: "Guide di cura",
    watchPoints: "Punti di attenzione",
    recommendedActions: "Azioni consigliate",
    speciesReviewed: "Specie analizzate",
    habitatPlan: "Piano habitat",
    candidates: "Specie consigliate",
    products: "Attrezzatura e prodotti",
    plants: "Piante",
    guidesSection: "Guide correlate",
    advisory: "Risultato indicativo — verifica animali reali, attrezzatura e chimica dell'acqua.",
    calculationAdvisory: "Calcolo indicativo — verifica input, unità, etichette dei prodotti e condizioni reali del sistema.",
    calculatedResult: "Risultato calcolato",
    incompleteCalculation: "Il calcolo richiede dati più completi prima di produrre un risultato affidabile.",
    inputsAndAssumptions: "Input e presupposti",
    resultCount: (count: number) => `${count} risultat${count === 1 ? "o" : "i"} pubblic${count === 1 ? "o" : "i"}`,
    toolResult: "Risultato Atlarium",
    compatibility: "Valutazione di compatibilità",
    careFollowUp: (title: string) => `Spiega le implicazioni di cura più importanti per ${title} usando il risultato Atlarium qui sopra.`,
    productFollowUp: (title: string) => `Spiega i criteri più importanti di scelta e dimensionamento per ${title} usando il risultato Atlarium qui sopra.`,
    compatibilityFollowUp: (level: string) => `Spiega come gestire in sicurezza questo risultato di compatibilità: ${level}.`,
    habitatFollowUp: "Affina questo piano habitat Atlarium mantenendolo in sola lettura.",
    diagnosticFollowUp: (title: string) => `Spiega i prossimi controlli più sicuri per questo risultato diagnostico Atlarium: ${title}.`,
    metricLabel: (label: string) => localizedLabel("it", label),
    statusLabel: (status: string) => localizedStatus("it", status),
  },
  es: {
    fieldGuide: "Guía de campo del hábitat",
    readOnly: "Solo lectura",
    diagnosticProfile: "Perfil diagnóstico",
    productProfile: "Perfil del producto",
    overview: "Descripción general",
    specifications: "Especificaciones",
    symptoms: "Síntomas",
    likelyCauses: "Causas probables",
    treatment: "Intervención",
    prevention: "Prevención",
    fertilization: "Fertilización",
    waitingTitle: "Preparando la vista del hábitat",
    waitingBody: "Atlarium está convirtiendo el resultado de la herramienta en una guía legible.",
    emptyTitle: "No hay datos del hábitat para mostrar",
    emptyBody: "Pide a ChatGPT una búsqueda, perfil, compatibilidad o cálculo de Atlarium.",
    errorTitle: "No se pudo mostrar el resultado",
    errorBody: "La respuesta original de Atlarium sigue disponible en la conversación.",
    details: "Ver detalles",
    expand: "Ampliar",
    collapse: "Volver a inline",
    askMore: "Pedir más detalles",
    water: "Parámetros del agua",
    guides: "Guías de cuidado",
    watchPoints: "Puntos de atención",
    recommendedActions: "Acciones recomendadas",
    speciesReviewed: "Especies revisadas",
    habitatPlan: "Plan de hábitat",
    candidates: "Especies recomendadas",
    products: "Equipos y productos",
    plants: "Plantas",
    guidesSection: "Guías relacionadas",
    advisory: "Resultado orientativo — verifica animales, equipo y química del agua reales.",
    calculationAdvisory: "Cálculo orientativo — verifica datos, unidades, etiquetas de productos y condiciones reales del sistema.",
    calculatedResult: "Resultado calculado",
    incompleteCalculation: "El cálculo necesita datos más completos antes de producir un resultado fiable.",
    inputsAndAssumptions: "Datos y supuestos",
    resultCount: (count: number) => `${count} resultado${count === 1 ? "" : "s"} público${count === 1 ? "" : "s"}`,
    toolResult: "Resultado de Atlarium",
    compatibility: "Revisión de compatibilidad",
    careFollowUp: (title: string) => `Explica las implicaciones de cuidado más importantes para ${title} usando el resultado de Atlarium anterior.`,
    productFollowUp: (title: string) => `Explica los criterios más importantes de selección y dimensionamiento para ${title} usando el resultado de Atlarium anterior.`,
    compatibilityFollowUp: (level: string) => `Explica cómo gestionar con seguridad este resultado de compatibilidad: ${level}.`,
    habitatFollowUp: "Afina este plan de hábitat de Atlarium manteniéndolo en modo de solo lectura.",
    diagnosticFollowUp: (title: string) => `Explica las siguientes comprobaciones más seguras para este resultado diagnóstico de Atlarium: ${title}.`,
    metricLabel: (label: string) => localizedLabel("es", label),
    statusLabel: (status: string) => localizedStatus("es", status),
  },
} as const;

export function languageFrom(value: unknown): Language {
  const normalized = String(value ?? "").toLowerCase();
  if (normalized.startsWith("it")) return "it";
  if (normalized.startsWith("es")) return "es";
  return "en";
}

export function useCopy(language: Language) {
  return copy[language];
}
